version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true

  saga:
    build: .
    container_name: saga-microservices
    depends_on:
      - kafka
    ports:
      - "3000:3000"  # Order Service
      - "3001:3001"  # Payment Service
      - "3002:3002"  # Orchestrator Service
      - "3003:3003"  # WebSocket Service
      - "3004:3004"  # Frontend
    environment:
      - KAFKA_BROKER=kafka:9092
      - MONGODB_URI=mongodb+srv://ismailyasser106:Qq123456789@aiu.bwzvhcr.mongodb.net/orderdb
      - NODE_ENV=production
    volumes:
      - ./logs:/app/logs
    command: ["/app/start-all-services.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
